INSERT INTO tb_usuarios(nombre_usuario, activado_usuario, fecha_registro_usuario) VALUES('Administrador', '1', NOW());
INSERT INTO tb_usuarios(nombre_usuario, activado_usuario, fecha_registro_usuario) VALUES('Cliente', '1', NOW());
INSERT INTO tb_usuarios(nombre_usuario, activado_usuario, fecha_registro_usuario) VALUES('Veterinario', '1', NOW());
INSERT INTO tb_usuarios(nombre_usuario, activado_usuario, fecha_registro_usuario) VALUES('Visitante', '1', NOW());

INSERT INTO tb_especies(nombre_especie, activado_especie, fecha_registro_especie) VALUES('Perro', '1', NOW());
INSERT INTO tb_especies(nombre_especie, activado_especie, fecha_registro_especie) VALUES('Gato', '1', NOW());
INSERT INTO tb_especies(nombre_especie, activado_especie, fecha_registro_especie) VALUES('Otro', '1', NOW());

INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Affenpinscher', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Afgano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Airedale Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Akita', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('American Eskimo Dog', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('American Staffordshire Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Australian Cattle Dog', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Azawakh', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Barbet', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Basenji', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Basset Hound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Beagle', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Beauceron', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bedlington Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bergamasco', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bernés de la Montaña', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bichon Frise', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bichón Habanero', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bichón Habanero', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Black Russian Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bloodhound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bluetick Coonhound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bobtail', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Boerboel', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Border Collie', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Border Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Borzoi', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Boston Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bouvier des Flandres', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bóxer', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Boykin Spaniel', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Braco Alemán Pelo Corto', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Braco Alemán Pelo Duro', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Braco Italiano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Briard', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Brittany Spaniel', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Broholmer', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Buhund Noruego', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bull Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bulldog Francés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bulldog Inglés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bulldog Americano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bullmastin', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bullterrier Miniatura', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cairn Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Canaan', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cardigan Welsh Corgi', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Catahoula Leopard Dog', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cavalier King Charles Spaniel', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cesky Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Chesapeake Bay Retriever', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Chihuahua', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Chin Japones', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Chow Chow', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cirneco dell´Etna', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Clumber Spaniel', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cocker Spaniel Americano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cocker Spaniel Inglés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Collie', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Collie Barbudo', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Coonhound de Redbone', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Coonhound Inglés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Coonhound Negro y Fuego', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Crestado Chino', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Dachshund (Salchicha)', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Dálmata', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Dandie Dinmont Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Deerhound Escocés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Doberman', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Dogo Argentino', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Dogue des Bordeaux', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('East Siberian Laika', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Faraón Hound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Field Spaniel', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Fila Brasileiro', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Finnish Lapphund', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Fox Terrier (Toy)', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Fox Terrier de Pelo Duro', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Fox Terrier de Pelo Liso', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Foxhound Américano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Foxhound Inglés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Galgo Español', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Galgo Italiano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('German Hunting Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Glen of Imaal Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Golden Retriever', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Gordon Setter', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Gran Danés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Gran Pirineo', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Gran Suizo de la Montaña', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Greenland Dog', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Greyhound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Griffon de Bruselas', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Harrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Husky Siberiano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Icelandic Sheepdog', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Jack Russell Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Kai', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Kangal', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Keeshound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Kelpie Australiano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Kerry Blue Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Komondor', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Kuvasz', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Labrador Retriever', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Lakeland Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Leonberger', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Lhasa Apso', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Löwchen', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Lundenhund Noruego', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Malamute de Alaska', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Maltese', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Manchester Terrier (Toy)', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Manchester Terrier Estandár', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Mastín', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Mastín Napolitano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Mastín Tibetano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Mudi', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Norfolk Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Norwegian Elkhound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Norwich Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Nova Scotia Duck Tolling Retri', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Otterhound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Papillon', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Parson Russell Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pastor Alemán', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pastor Australiano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pastor Belga de Lakenois', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pastor Belga Malinois', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pastor Belga Tervueren', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pastor de Anatolia', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pastor de los Pirineos', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pastor de Maremma', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pekinés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pembroke Welsh Corgi', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Perro de Aguas Americano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Perro de Aguas Español', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Perro de Aguas Irlandés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Perro de Aguas Portugués', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Perro sin Pelo del Perú', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Petit Basset Griffon Vendéen', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pinscher Alemán', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pinscher Miniatura', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pit Bull Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Plott Hound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Podenco Ibicenico', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Podenco Portugués Pequeño', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pointer', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Polish Lowland Sheepdog', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pomerania', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Poodle (Caniche)', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Poodle Gigante', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Poodle Toy (Caniche)', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pug (Carlino)', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Puli', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pumi', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Rat Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Retriever de Pelo Liso', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Retriever de Pelo Rizado', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Rhodesian Ridgeback', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Rottweiler', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Russian European Laika', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Saluki', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Samoyedo', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('San Bernardo', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Schipperke', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Schnauzer Estándard', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Schnauzer Gigante', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Schnauzer Miniatura', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Scottish Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Sealyham Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Setter Inglés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Setter Irlandés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Setter Rojo y Blanco Irlandés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Shar Pei', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Shetland Sheepdog', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Shiba Inu', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Shih Tzu', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Silky Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Skye Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Sloughi', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Soft Coated Wheaten Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Spaniel Tibetano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Spinone Italiano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Spitz', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Springer Spaniel Inglés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Staffordhire Bull Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Sussex Spaniel', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Swedish Elkhound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Swedish Lapphund', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Swedish Vallhund', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Terranova', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Terrier Australiano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Terrier Brasileiro', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Terrier Galés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Terrier Irlandés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Terrier Japones', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Terrier Tibetano', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Tosa Inu', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Toy Spaniel Inglés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Treeing Walker Coonhound', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Vizsla', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Weimaraner', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Welsh Springer Spaniel', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('West Highland White Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('West Siberian Laika', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Whippet', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Wirehaired Pointing Griffon', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Wolfhound Irlandés', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Xoloitzcuintle', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Yorkshire Terrier', '1', NOW(), '1');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Otro', '1', NOW(), '1');

INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Abisinio (Abyssinian)', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Angora (Turco)', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Asiático Humo (Atigrado)', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Azul Ruso', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Balinés (Balinese)', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bengala o Bengalí', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bobtail Japonés', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bombay', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Bosque de Noruega', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Brasileño de Pelo Corto', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Británico de Pelo Largo', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Británico de Pelo Corto', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('California Spangled Cat', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cartujo (Chartreux)', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cornish Rex', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Curl Americano', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Cymric', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Doméstico Común o Mestizo', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('El Burmés', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Esfinge', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Exótico', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Fold Escocés', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Foldex', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Himalayo', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Javanés', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Korat', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Maine Coon', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Manx', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Mau Egipcio', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Munchkin', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Nebelung', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Oriental', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pelicorto Americano', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pelicorto Europeo', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Persa', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Pixie Bob', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Ragdoll', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Rex', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Sagrado de Birmania (Birmano)', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Sagrados-de-Birmania', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Siamés (Siamese)', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Singapur (Singapura)', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Skogkatt', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Snowshoe', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Sokoke', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Somalí', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Tonquinés', '1', NOW(), '2');
INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Otro', '1', NOW(), '2');

INSERT INTO tb_razas(nombre_raza, activado_raza, fecha_registro_raza, id_especie) VALUES('Otro', '1', NOW(), '3');

SELECT * FROM tb_mascotas;
SELECT * FROM tb_clientes;
SELECT * FROM tb_especies;
SELECT * FROM tb_razas;
SELECT * FROM tb_registros_vacunas;
SELECT * FROM tb_veterinarios;
SELECT * FROM tb_veterinarias;

insert into tb_vacunas(nombre_vacuna, activado_vacuna, fecha_registro_vacuna, id_especie) values('penta', '1', NOW(), '1');

insert into tb_registros_vacunas(laboratorio_rvacuna, cepa_rvacuna, lote_rvacuna, fecha_exp_rvacuna, fecha_apli_rvacuna, dosis_rvacuna, id_mascota, id_vacuna) values('laboratorio', 'cepa', 'lote', NOW(), NOW(), '1', '2', '1');


DELETE FROM tb_clientes WHERE id_cliente = 2;

UPDATE tb_clientes SET contrasena_cliente = md5('1') WHERE id_cliente = 2;

UPDATE tb_mascotas SET nombre_mascota = 'matias', identificacion_mascota = '12345', fecha_nacimiento_mascota = NOW(), direccion_mascota = '123', path_foto_mascota = '///', path_foto_cvacunas = '///', activado_mascota = '1', id_cliente = '1', id_especie = '1', id_raza = '1' WHERE id_mascota = '1';

SELECT * FROM tb_visitas_veterinarias h, tb_veterinarias va, tb_veterinarios vo WHERE id_mascota = '1' AND h.id_veterinaria = va.id_veterinaria AND h.id_veterinario = vo.id_veterinario;

SELECT * FROM tb_veterinarias WHERE id_veterinario = 1 AND activado_veterinaria = '1';

UPDATE tb_veterinarias SET nombre_veterinaria = '2', nit_veterinaria = '2', direccion_veterinaria = '2', telefono_veterinaria = '2', celular_veterinaria = '2', path_foto_veterinaria = '2', activado_veterinaria = '1', id_veterinario = '1' WHERE id_veterinaria = '1';